name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]   # Run workflow when pushing to main branch
  workflow_dispatch:        # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # needed to push to GHCR

    steps:
      # Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/taskpal:latest
            ghcr.io/${{ github.repository_owner }}/taskpal:${{ github.sha }}
